// finance-editor.test.mjs — jsdom coverage for tools/finance.html.
import { JSDOM } from 'jsdom';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here=dirname(fileURLToPath(import.meta.url));
const html=readFileSync(join(here,'finance.html'),'utf8');
const finance={rent:{base:100,perFloorTile:2,byPropertyType:{condo:20,basement:-10,townhouse:50,house:100,penthouse:250}},bills:[{id:'phone',name:'Phone',base:10,perAssetValue:.1}],overdueDays:3,tooLateDays:7,negativeGraceDays:2};
const assets={assets:[{id:'chair',buyPrice:100}]};
const tuning={map:{active:'condo'},credit:{min:300,max:900,startingScore:500,onTimePaymentDelta:8,overdueDelta:-20,debtEntryDelta:-10,debtDailyDelta:-3,repoDelta:-100,lowScoreDebtWindowFactor:.75,highScoreDebtWindowFactor:1.5,historyLimit:6}};
const happiness={components:[{var:'needs.hunger',weight:2,min:0,max:100}],visaStatusRanks:{visitor:0,lmia:1},states:[{id:'low',atLeast:0,label:'Low',icon:'/icons/sad.svg'},{id:'high',atLeast:80,label:'High',icon:'/icons/happy.svg'}],stateDisplay:'both'};
const stats={needs:[{id:'hunger',name:'Hunger'}],skills:[{id:'cooking',name:'Cooking'}]};
const simstate={variables:[{id:'visaStatus',name:'Visa Status'},{id:'job',name:'Job'}]};
const visas={visas:[{id:'visitor',name:'Visitor'},{id:'lmia',name:'LMIA'}]};
const map={id:'condo',propertyType:'condo',gridSize:1,bounds:{w:2,h:2},floors:[{polygon:[[0,0],[2,0],[2,2],[0,2]]}],placedObjects:[{asset:'chair'}]};
const rawPuts={};
const fetchMock=async(url,opts={})=>{if(String(url)==='/api/icons')return{ok:true,status:200,json:async()=>['icons/happy.svg','icons/neutral.svg','icons/sad.svg']};const path=String(url).replace('/api/data/','');if(opts.method==='PUT'){rawPuts[path]=opts.body;return{ok:true,status:200,json:async()=>({})};}const body={'finance.json':finance,'assets.json':assets,'tuning.json':tuning,'happiness.json':happiness,'stats.json':stats,'simstate.json':simstate,'visas.json':visas,'maps/condo.json':map}[path];return{ok:!!body,status:body?200:404,json:async()=>structuredClone(body)};};
const dom=new JSDOM(html,{url:'http://localhost:5173/tools/finance.html',runScripts:'dangerously',beforeParse(window){window.fetch=fetchMock;}});
const {window}=dom,doc=window.document; await new Promise((resolve)=>setTimeout(resolve,50));
let failures=0;function check(cond,msg){if(cond)console.log('  ok  '+msg);else{failures++;console.error('FAIL  '+msg);}}function fire(el,type){el.dispatchEvent(new window.Event(type,{bubbles:true}));}

check(!!window.FinanceEditor,'plain script exposes window.FinanceEditor');
check(doc.querySelector('input[data-path="rent.base"]').value==='100' && doc.querySelectorAll('.bill').length===1,'renders rent and bill formula fields');
check(doc.querySelector('input[data-path="rent.byPropertyType.penthouse"]').value==='250','renders complete property-type table');
check(doc.querySelector('input[data-path="credit.startingScore"]').value==='500','renders tuning.credit fields');
check(doc.querySelectorAll('.happiness-row[data-component-index]').length===1&&doc.querySelector('select[data-path="happiness.components.0.var"]').value==='needs.hunger','renders happiness components with dropdown variables');
check(!doc.querySelector('input[data-path="happiness.components.0.var"]'),'happiness variable ids are never free-typed');
check(doc.querySelector('input[data-path="happiness.visaStatusRanks.lmia"]').value==='1','renders editable visa status ranks');
check(doc.querySelectorAll('.state-row[data-state-index]').length===2&&doc.getElementById('stateDisplay').value==='both','renders designer-defined happiness states and display mode');
check([...doc.querySelectorAll('#happinessIconOptions option')].some((x)=>x.value==='/icons/happy.svg'),'icon dropdown is fed by /api/icons and normalized to public URLs');
let resolverCalls=0;window.FinanceEditor.setHappinessResolver((value,states)=>{resolverCalls++;return [...(states||[])].filter((x)=>value>=x.atLeast).sort((a,b)=>b.atLeast-a.atLeast)[0]||null;},(mode)=>({icon:mode!=='text',text:mode!=='icon'}));
const stateValue=doc.getElementById('happinessPreviewValue');stateValue.value='80';fire(stateValue,'input');
check(resolverCalls>0&&doc.getElementById('happinessStatePreview').dataset.stateId==='high','live value-to-state preview calls the injected real-resolver bridge');
check(html.includes("import { happinessStateDisplay, happinessStateFor } from '/game/happiness.ts'"),'browser module wires preview through the real happiness resolver');
doc.getElementById('addHappinessState').click();
check(window.FinanceEditor.state.happiness.states.length===3&&doc.querySelectorAll('.state-row').length===3,'state add is data-backed');
const addedLabel=doc.querySelector('input[data-path="happiness.states.2.label"]');addedLabel.value='Custom';fire(addedLabel,'input');
doc.querySelector('.state-row[data-state-index="2"] [data-action="state-up"]').click();
check(window.FinanceEditor.state.happiness.states[1].label==='Custom','state reorder preserves the complete authored row');
doc.querySelector('.state-row[data-state-index="1"] [data-action="remove-state"]').click();
check(window.FinanceEditor.state.happiness.states.length===2&&!window.FinanceEditor.state.happiness.states.some((x)=>x.label==='Custom'),'state remove updates the array safely');
const display=doc.getElementById('stateDisplay');display.value='text';fire(display,'change');
check(window.FinanceEditor.state.happiness.stateDisplay==='text','state display selector round-trips into happiness data');
window.FinanceEditor.setCompute((f,ctx)=>({floorTileCount:4,totalAssetValue:100,rent:f.rent.base+f.rent.perFloorTile*4+f.rent.byPropertyType[ctx.map.propertyType],bills:f.bills.map((bill)=>({...bill,amount:bill.base+bill.perAssetValue*100}))}));
check(doc.querySelector('[data-preview-id="rent"]').textContent==='§128' && doc.querySelector('[data-preview-id="phone"]').textContent==='§20','live preview renders computed rent and bill numbers');
const base=doc.querySelector('input[data-path="rent.base"]');base.value='150';fire(base,'input');
const grace=doc.querySelector('input[data-path="negativeGraceDays"]');grace.value='5';fire(grace,'input');
const repo=doc.querySelector('input[data-path="credit.repoDelta"]');repo.value='-125';fire(repo,'input');
const happyWeight=doc.querySelector('input[data-path="happiness.components.0.weight"]');happyWeight.value='4';fire(happyWeight,'input');
check(window.FinanceEditor.state.finance.rent.base===150 && window.FinanceEditor.state.finance.negativeGraceDays===5,'edits round-trip into finance schema');
check(window.FinanceEditor.state.tuning.credit.repoDelta===-125,'credit edits round-trip into tuning schema');
check(window.FinanceEditor.state.happiness.components[0].weight===4,'happiness edits round-trip into happiness schema');
check(doc.querySelector('[data-preview-id="rent"]').textContent==='§178','live preview refreshes after an edit');
doc.getElementById('save').click();await new Promise((resolve)=>setTimeout(resolve,20));
const saved=JSON.parse(rawPuts['finance.json']),savedTuning=JSON.parse(rawPuts['tuning.json']),savedHappiness=JSON.parse(rawPuts['happiness.json']);check(saved.rent.base===150&&saved.negativeGraceDays===5,'finance PUT contains edited values');
check(savedTuning.credit.repoDelta===-125,'tuning PUT contains edited credit values');
check(savedHappiness.components[0].weight===4&&savedHappiness.stateDisplay==='text'&&savedHappiness.states.length===2,'happiness PUT contains formula plus complete state CRUD shape');
check(rawPuts['finance.json']===JSON.stringify(saved,null,2)&&rawPuts['tuning.json']===JSON.stringify(savedTuning,null,2)&&rawPuts['happiness.json']===JSON.stringify(savedHappiness,null,2),'saves use exact pretty whole-file JSON');
const degradedFetch=async(url,opts={})=>String(url)==='/api/icons'?{ok:false,status:500,json:async()=>[]} : fetchMock(url,opts);
const degradedDom=new JSDOM(html,{url:'http://localhost:5173/tools/finance.html',runScripts:'dangerously',beforeParse(w){w.fetch=degradedFetch;w.console.warn=()=>{};}});await new Promise((resolve)=>setTimeout(resolve,50));
check(degradedDom.window.document.getElementById('status').textContent==='Loaded'&&degradedDom.window.FinanceEditor.state.icons.length===0&&degradedDom.window.document.querySelectorAll('.state-row').length===2,'missing /api/icons degrades gracefully without blocking state editing');
if(failures){console.error(`\n${failures} failure(s)`);process.exit(1);}console.log('\nall finance editor tests passed');
